# Based on code by Kristoffer Carlsson:
# https://github.com/JuliaLang/julia/issues/47709#issuecomment-2388629772

module MethodURL

using Base:
    UUID,
    inbase,
    load_path,
    loaded_modules,
    fixup_stdlib_path,
    env_project_file,
    project_file_manifest_path,
    parsed_toml,
    project_names
using RegistryInstances: reachable_registries, registry_info
using Downloads: request, Response

export url

const JULIA_REPO = "https://github.com/JuliaLang/julia"

"""
    url(m::Method)

Return a vector of URLs pointing to the source code of method `m`.

URLs are constructed according to the origin of the method:
- methods from `Base`, `Core` and stdlibs link to the matching release
  in the JuliaLang/julia repository, or, for stdlibs that are vendored from
  their own repository, to the exact vendored commit in that repository
- methods from packages tracked by a local path (e.g. `Pkg.develop`ed) link
  to the local file via a `file://` URL
- methods from packages added by URL link to that repository at the tracked revision
- methods from registered packages link to the repository listed in the registry
  at the version tag of the loaded package; one URL is returned per registry
  in which the package is found
- methods whose files belong to a different loaded package than their parent
  module (e.g. JLL package methods generated by macros from JLLWrappers)
  link into the package that contains the file

Constructing stdlib URLs requires fetching a `<name>.version` file from the
JuliaLang/julia repository, so calling `url` on stdlib methods can access the
network. The result of this lookup is cached for the lifetime of the session.

Throw an error if no URL can be constructed.
"""
function url(m::Method)
    M = parentmodule(m)
    file = fixup_stdlib_path(String(m.file))
    line = m.line

    if M === Core || inbase(M)
        return [forge_url(JULIA_REPO, julia_ref(), :commit, "base/$file", line)]
    end

    dir = _pkgdir(M)
    if !file_in_dir(file, dir)
        # Methods can be defined in files of another package, e.g. methods of
        # JLL packages generated by macros from JLLWrappers. Attribute such
        # methods to the loaded package that contains the file.
        owner = module_owning_file(file)
        if !isnothing(owner)
            M = owner
            dir = _pkgdir(M)
        end
    end
    name, uuid = project_name_uuid(dir)

    entry = manifest_entry(uuid)
    if !isnothing(entry) && haskey(entry, "path")
        # Package is tracked by a local path, e.g. through `Pkg.develop`
        return [file_url(file, line)]
    end

    path = path_in_package(dir, file)

    if !isnothing(entry) && haskey(entry, "repo-url")
        # Package was added by URL, e.g. through `Pkg.add(; url=...)`
        return [url_from_manifest_repo(entry, M, path, line)]
    end

    if startswith(dir, Sys.STDLIB)
        # Checked before registries: some stdlibs are also registered, but only
        # the vendored commit is guaranteed to match the loaded source code.
        return [stdlib_url(basename(dir), path, line)]
    end

    repos = repos_package(uuid)
    if !isempty(repos)
        # Package is registered: one URL per registry it is found in
        version = _pkgversion(M)
        return [registry_url(repo, subdir, name, version, path, line) for (repo, subdir) in repos]
    end

    throw(
        ArgumentError(
            "Failed to construct URL for method `$m`: " *
                "package $name [$uuid] was not found in any manifest, registry, or the stdlib.",
        ),
    )
end

# Ref in the JuliaLang/julia repository corresponding to the running Julia version.
function julia_ref()
    commit = Base.GIT_VERSION_INFO.commit
    return isempty(commit) ? "v$VERSION" : commit
end

# Construct a URL to a file and line on a known git forge.
# `kind` distinguishes the type of `ref` (`:tag`, `:commit` or `:branch`)
# for forges whose URL scheme depends on it.
function forge_url(
        repo::AbstractString,
        ref::AbstractString,
        kind::Symbol,
        path::AbstractString,
        line::Integer,
    )
    repo = chopsuffix(normalize_repo(repo), ".git")
    host_match = match(r"^https://([^/]+)", repo)
    host = isnothing(host_match) ? "" : host_match[1]::SubString{String}
    if host == "github.com"
        # https://github.com/owner/Package.jl/blob/v0.1.0/src/foo.jl#L42
        return "$repo/blob/$ref/$path#L$line"
    elseif host == "gitlab.com" || startswith(host, "gitlab.")
        # GitLab.com and self-hosted GitLab instances (e.g. gitlab.gwdg.de)
        # https://gitlab.com/owner/Package.jl/-/blob/v0.1.0/src/foo.jl#L42
        return "$repo/-/blob/$ref/$path#L$line"
    elseif host == "git.sr.ht"
        # https://git.sr.ht/~owner/Package.jl/tree/v0.1.0/item/src/foo.jl#L42
        return "$repo/tree/$ref/item/$path#L$line"
    elseif host == "bitbucket.org"
        # https://bitbucket.org/owner/Package.jl/src/v0.1.0/src/foo.jl#lines-42
        return "$repo/src/$ref/$path#lines-$line"
    elseif host == "codeberg.org"
        # https://codeberg.org/owner/Package.jl/src/tag/v0.1.0/src/foo.jl#L42
        segment = kind === :tag ? "tag" : kind === :commit ? "commit" : "branch"
        return "$repo/src/$segment/$ref/$path#L$line"
    else
        throw(ArgumentError("Failed to construct URL for unknown git forge of repository $repo."))
    end
end

# Turn scp-like git remotes (`git@github.com:owner/Repo.jl.git`) into HTTPS URLs.
function normalize_repo(repo::AbstractString)
    m = match(r"^git@([^:]+):(.+)$", repo)
    return isnothing(m) ? String(repo) : "https://$(m[1])/$(m[2])"
end

# RFC 8089 file URI for a local file: forward slashes, a leading slash
# (also before Windows drive letters) and percent-encoded spaces.
function file_url(file::AbstractString, line::Integer)
    if !isabspath(file)
        throw(ArgumentError("Failed to construct URL: $file is not an absolute file path."))
    end
    path = replace(file, '\\' => '/', ' ' => "%20")
    if !startswith(path, "/")
        path = "/" * path
    end
    return "file://$path#L$line"
end

# Path of `file` relative to the package root directory `dir`,
# joined with forward slashes for use in URLs.
function path_in_package(dir::AbstractString, file::AbstractString)
    parts = splitpath(relpath(file, dir))
    if !isabspath(file) || first(parts) == ".."
        throw(ArgumentError("Failed to construct URL: file $file is not part of the package at $dir."))
    end
    return join(parts, "/")
end

# Whether the absolute path `file` lies inside the directory `dir`.
function file_in_dir(file::AbstractString, dir::AbstractString)
    isabspath(file) || return false
    return first(splitpath(relpath(file, dir))) != ".."
end

# Module of the loaded package whose package directory contains `file`,
# or `nothing` if `file` is not part of any loaded package.
# Of nested package directories, the innermost match wins.
function module_owning_file(file::AbstractString)
    owner = nothing
    owner_dir = ""
    for M in values(loaded_modules)
        dir = pkgdir(M)
        isnothing(dir) && continue
        if file_in_dir(file, dir) && length(dir) > length(owner_dir)
            owner, owner_dir = M, dir
        end
    end
    return owner
end

# Like `pkgdir`, but throws instead of returning `nothing`
function _pkgdir(M::Module)
    dir = pkgdir(M)
    isnothing(dir) && throw(ArgumentError("Failed to find package directory of module $M."))
    return dir
end

# Like `pkgversion`, but throws instead of returning `nothing`
function _pkgversion(M::Module)
    version = pkgversion(M)
    isnothing(version) && throw(ArgumentError("Failed to find version of package $M."))
    return version
end

# Package name and UUID from the Project.toml in the package directory.
# Unlike `Base.PkgId`, this also gives the parent package for package extensions,
# whose files live in the parent package repository.
function project_name_uuid(dir::AbstractString)
    for project in project_names # ("JuliaProject.toml", "Project.toml")
        file = joinpath(dir, project)
        isfile(file) || continue
        d = parsed_toml(file)
        name = get(d, "name", nothing)
        uuid = get(d, "uuid", nothing)
        if name isa String && uuid isa String
            return name, UUID(uuid)
        end
    end
    throw(ArgumentError("Failed to find name and UUID of the package at $dir."))
end

# Manifest entry of the package `uuid`, searched through all environments
# in the load path, or `nothing` if the package is not listed in any manifest.
function manifest_entry(uuid::UUID)
    for env in load_path()
        project = env_project_file(env)
        project isa String || continue
        manifest = project_file_manifest_path(project)
        manifest isa String || continue
        isfile(manifest) || continue
        raw = parsed_toml(manifest)
        deps = get(raw, "deps", raw) # manifest format 2 stores entries under "deps"
        deps isa AbstractDict || continue
        for entries in values(deps)
            entries isa AbstractVector || continue
            for entry in entries
                entry isa AbstractDict || continue
                if get(entry, "uuid", nothing) == string(uuid)
                    return entry
                end
            end
        end
    end
    return nothing
end

# URL into the repository a package was added from by URL,
# at the tracked revision if one is recorded, otherwise at the version tag.
function url_from_manifest_repo(
        entry::AbstractDict, M::Module, path::AbstractString, line::Integer
    )
    repo = entry["repo-url"]
    subdir = get(entry, "repo-subdir", nothing)
    if subdir isa String
        path = "$subdir/$path"
    end
    rev = get(entry, "repo-rev", nothing)
    if rev isa String
        kind = occursin(r"^[0-9a-f]{40}$", rev) ? :commit : :branch
        return forge_url(repo, rev, kind, path, line)
    else
        return forge_url(repo, "v$(_pkgversion(M))", :tag, path, line)
    end
end

# Find repository and subdirectory in reachable registries by looking up UUID
function repos_package(uuid::UUID)
    repos = Tuple{String, Union{Nothing, String}}[]
    for reg in reachable_registries()
        entry = get(reg, uuid, nothing)
        if !isnothing(entry)
            info = registry_info(entry)
            info.repo isa String && push!(repos, (info.repo, info.subdir))
        end
    end
    return repos
end

# URL into the registered repository of a package at its version tag.
# Packages in a monorepo subdirectory are tagged `<name>-v<version>`
# (the TagBot convention) and their path is prefixed with the subdirectory.
# JLL repositories drop the `_jll` suffix from release tags,
# e.g. Bzip2_jll v1.0.9+0 is tagged `Bzip2-v1.0.9+0`.
function registry_url(
        repo::AbstractString,
        subdir::Union{Nothing, AbstractString},
        name::AbstractString,
        version::VersionNumber,
        path::AbstractString,
        line::Integer,
    )
    if !isnothing(subdir)
        return forge_url(repo, "$name-v$version", :tag, "$subdir/$path", line)
    elseif endswith(name, "_jll")
        return forge_url(repo, "$(chopsuffix(name, "_jll"))-v$version", :tag, path, line)
    else
        return forge_url(repo, "v$version", :tag, path, line)
    end
end

# Some stdlibs are vendored from their own repository (e.g. Pkg.jl) and their
# source code is not part of the JuliaLang/julia repository. The exact vendored
# commit is recorded in `stdlib/<name>.version` files in the julia repository,
# which are not shipped with Julia and therefore have to be fetched.
# Cache: stdlib name => `nothing` (source is in the julia repo) or (repo, sha).
const STDLIB_VERSION_CACHE = Dict{String, Union{Nothing, Tuple{String, String}}}()
const STDLIB_VERSION_LOCK = ReentrantLock()

function stdlib_repo_and_sha(name::AbstractString)
    return lock(STDLIB_VERSION_LOCK) do
        get!(STDLIB_VERSION_CACHE, name) do
            fetch_stdlib_repo_and_sha(name)
        end
    end
end

function fetch_stdlib_repo_and_sha(name::AbstractString)
    version_url = "https://raw.githubusercontent.com/JuliaLang/julia/$(julia_ref())/stdlib/$name.version"
    buffer = IOBuffer()
    response = request(version_url; output = buffer, throw = false)
    response isa Response || throw(response) # RequestError, e.g. when offline
    response.status == 404 && return nothing # stdlib source is part of the julia repository
    if response.status != 200
        error("Failed to fetch stdlib version file at $version_url (HTTP status $(response.status)).")
    end
    content = String(take!(buffer))
    sha = match(r"_SHA1\s*:?=\s*([0-9a-f]{40})", content)
    repo = match(r"_GIT_URL\s*:?=\s*(\S+)", content)
    if isnothing(sha) || isnothing(repo)
        error("Failed to parse stdlib version file at $version_url.")
    end
    return (String(something(repo[1])), String(something(sha[1])))
end

# URL of a stdlib file, either in the JuliaLang/julia repository or,
# for vendored stdlibs, in their own repository at the exact vendored commit.
function stdlib_url(name::AbstractString, path::AbstractString, line::Integer)
    repo_and_sha = stdlib_repo_and_sha(name)
    if isnothing(repo_and_sha)
        return forge_url(JULIA_REPO, julia_ref(), :commit, "stdlib/$name/$path", line)
    else
        repo, sha = repo_and_sha
        return forge_url(repo, sha, :commit, path, line)
    end
end

end # module
